Refactor download location handling
We now handle many more cases and show clear error messages when using
conflicting features.

diff --git a/hib-dlagent b/hib-dlagent
--- a/hib-dlagent
+++ b/hib-dlagent
@@ -9,7 +9,6 @@ COOKIE_JAR=
 FILE=
 DESTINATION=
 DOWNLOAD=1
-LISTING_PAGES=()
 USERNAME=
 PASSWORD=
 KEYS=()
@@ -32,13 +31,15 @@ usage() {
   echo
   echo "Usage: $0 [OPTIONS] FILE"
   echo "Options:"
-  echo " -d         Storage directory to look first"
+  echo " -d <dir>   Directory for searching and saving files. The normal save"
+  echo "            location is still used, but will be a symbolic link"
   echo " -h         This help"
   echo " -k <key>   Search key's files. Use multiple times for multiple keys"
   echo " -o <file>  Name to use when saving file"
   echo " -p <pass>  Use pass to login. If specified multiple times, the last is"
   echo "            used"
-  echo " -s         Print URL to stdout instead of downloading"
+  echo " -s         Print URL to stdout instead of downloading. Incompatible"
+  echo "            with -d"
   echo " -u <user>  Use user to login. Search account's files. If specified"
   echo "            multiple times, the last is used"
   echo
@@ -46,6 +47,47 @@ usage() {
   echo "a key is associated with a HIB account then you must use -u/-p, since"
   echo "that key only works when logged into that account. It is not helpful to"
   echo "specify -k for bundles associated with an account."
+}
+
+handle_download() {
+  local SAVE_FILE="$1"
+  local LISTING_PAGES=()
+
+  COOKIE_JAR=$(mktemp)
+
+  if [ -n "$USERNAME" ]; then
+    login
+    LISTING_PAGES+=("$HOME_PAGE")
+  fi
+
+  for KEY in "${KEYS[@]}"; do
+    LISTING_PAGES+=("https://www.humblebundle.com/downloads?key=$KEY")
+  done
+
+  if [ -z "$LISTING_PAGES" ]; then
+    echo "You must specify at least one of -u and -k" >&2
+    exit 1
+  fi
+
+  local URL
+  for LISTING_PAGE in "${LISTING_PAGES[@]}"; do
+    URL=$(discover_url "$LISTING_PAGE")
+    if [ -n "$URL" ]; then break; fi
+  done
+
+  # Cookie no longer necessary.
+  rm "$COOKIE_JAR"
+
+  if [ ! -n "$URL" ]; then
+    echo "Could not find URL for file: $FILE" >&2
+    exit 2
+  fi
+
+  if [ $DOWNLOAD -eq 0 ]; then
+    echo "$URL"
+  else
+    /usr/bin/curl -C - --retry 3 --retry-delay 3 -o "$SAVE_FILE" "$URL"
+  fi
 }
 
 main() {
@@ -96,57 +138,54 @@ main() {
     exit 1
   fi
 
-  COOKIE_JAR=$(mktemp)
-  FILE="${1#hib://}"
-
-  if [ -z "$DESTINATION" ]; then
-    DESTINATION="${FILE##*/}"
-  fi
-
-  if [ -n "$STORAGE" ]; then
-    STORAGE_FILE=$(/usr/bin/find "$STORAGE" -name "$FILE")
-    if [ -n "$STORAGE_FILE" ]; then
-      echo "Found file: $STORAGE_FILE"
-      ln -s "$STORAGE_FILE" "$DESTINATION"
-      return;
-    fi
-  fi
-
-  if [ -n "$USERNAME" ]; then
-    login;
-    LISTING_PAGES+=("$HOME_PAGE")
-  fi
-
-  for KEY in "${KEYS[@]}"; do
-    LISTING_PAGES+=("https://www.humblebundle.com/downloads?key=$KEY")
-  done
-
-  if [ -z "$LISTING_PAGES" ]; then
-    echo "You must specify at least one of -u and -k" >&1
+  if [ $DOWNLOAD -eq 0 -a -n "$STORAGE" ]; then
+    echo "-s and -d are incompatible" >&2
     exit 1
   fi
 
-  for LISTING_PAGE in "${LISTING_PAGES[@]}"; do
-    URL=$(discover_url "$LISTING_PAGE")
-    if [ -n "$URL" ]; then break; fi
-  done
+  FILE="$1"
 
-  # Cookie no longer necessary.
-  rm "$COOKIE_JAR"
-
-  if [ ! -n "$URL" ]; then
-    echo "Could not find URL for file: $FILE" >&2
-    exit 2
+  if [ "$FILE" != "$(basename "$FILE")" ]; then
+    # We need a simple file name without any slashes. Instead of erroring, we
+    # strip the file name out so that hib://filename is a valid argument.
+    FILE=$(basename "$FILE")
+    # Since we are doing something fancy, give the user a clue that we modified
+    # their input.
+    echo "Searching for $FILE" >&2
   fi
 
-  if [ $DOWNLOAD -eq 0 ]; then
-    echo "$URL"
+  if [ -z "$DESTINATION" ]; then
+    DESTINATION="."
+  fi
+
+  if [ -d "$DESTINATION" ]; then
+    DESTINATION="$DESTINATION/$FILE"
+  fi
+
+  if [ -z "$STORAGE" ]; then
+    handle_download "$DESTINATION"
   else
-    if [ -n "$STORAGE" ]; then
-      ln -s "$STORAGE/$FILE" "$DESTINATION"
-      DESTINATION="$STORAGE/$FILE"
+    local STORAGE_FILE
+    STORAGE_FILE=$(/usr/bin/find "$STORAGE" -name "$FILE")
+    if [ -z "$STORAGE_FILE" ]; then
+      STORAGE_FILE="$STORAGE/$FILE"
+      handle_download "$STORAGE_FILE"
     fi
-    /usr/bin/curl -C - --retry 3 --retry-delay 3 -o "$DESTINATION" "$URL"
+
+    if [ ! "$STORAGE_FILE" -ef "$DESTINATION" ]; then
+      ln -s "$STORAGE_FILE" "$DESTINATION"
+      if [ ! "$STORAGE_FILE" -ef "$DESTINATION" ]; then
+        # If DESTINATION is in a different directory than the CWD and STORAGE
+        # is a relative path, then ln -s will produce a broken link. To produce
+        # a valid link we resolve the path with readlink. This is unfortunate
+        # because having relative links is nicer and we will undo any symlinks
+        # in the path. Therefore, we detect when things have broken and only
+        # use readlink when we must.
+        STORAGE_FILE=$(/usr/bin/readlink -f "$STORAGE_FILE")
+        rm "$DESTINATION"
+        ln -s "$STORAGE_FILE" "$DESTINATION"
+      fi
+    fi
   fi
 }
 
